-- AlterTable: 2FA TOTP (RFC 6238)
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "totpEnabled"     BOOLEAN  NOT NULL DEFAULT false;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "totpSecret"      TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "totpBackupCodes" TEXT[]   NOT NULL DEFAULT ARRAY[]::TEXT[];
